### ISSUE TITLE
Small error `Interaction has already been acknowledged`

### ISSUE THREAD

**Issue by SENPAY98K** [RoaldDahl/Button-Handler#1]
It works fine
![image](https://user-images.githubusercontent.com/77079047/188252467-85970d66-17a7-4193-9a9b-bd2eda7dae9d.png)

but still drops an error
```
DiscordAPIError[40060]: Interaction has already been acknowledged.
    at SequentialHandler.runRequest (C:\Users\Administrator\Desktop\DJS14\node_modules\@discordjs\rest\dist\index.js:748:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (C:\Users\Administrator\Desktop\DJS14\node_modules\@discordjs\rest\dist\index.js:560:14)
    at async REST.request (C:\Users\Administrator\Desktop\DJS14\node_modules\@discordjs\rest\dist\index.js:1000:22)
    at async ButtonInteraction.reply (C:\Users\Administrator\Desktop\DJS14\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:110:5) {
  rawError: {
    message: 'Interaction has already been acknowledged.',
    code: 40060
  },
  code: 40060,
  status: 400,
  method: 'POST',
  url: 'https://discord.com/api/v10/interactions/1015448602040082522/aW50ZXJhY3Rpb246MTAxNTQ0ODYwMjA0MDA4MjUyMjo1eHAyT3JUZzJQajZ0VjdIVUFCd0w1Umw4RHVia3BIVmREcFYydmhHcmdleTVvVWpFYnc3TVFNdEpNR1FsWWxwWkFtZ1JuMjJwTHFFc1E2UkFtbzl0ekViUE1NbFJkTG9XQmR3NVNUd1kzUlBsSFB6TDlrZmczY0R6ZmpMSldDNQ/callback',
  requestBody: { files: [], json: { type: 4, data: [Object] } }
}
```

**Comment by RoaldDahl** [comment]
I'd say you done something wrong as it seems to work fine for everyone else, I've also just tested it myself

**Comment by SENPAY98K** [comment]
Here's the files
![image](https://user-images.githubusercontent.com/77079047/188253527-7823eda7-7f7b-45ed-89d6-de2c8c9186fb.png)

![image](https://user-images.githubusercontent.com/77079047/188253547-07125ebc-f14a-4c61-ae2d-f69c38e7da7c.png)

![image](https://user-images.githubusercontent.com/77079047/188253563-f50c9964-ea1a-44d1-a181-26e9ef7cdbc5.png)

**Comment by RoaldDahl** [comment]
whats your index.js look like

**Comment by SENPAY98K** [comment]
![image](https://user-images.githubusercontent.com/77079047/188254298-077e1193-34bf-40c8-be75-e160713304c0.png)

**Comment by SENPAY98K** [comment]
I only edited the ascii tables

**Comment by RoaldDahl** [comment]
I'm confused as to why it's doing that to you then, works for everyone else

**Comment by SENPAY98K** [comment]
I will try again and see

**Comment by RoaldDahl** [comment]
only thing i can think of is you have two instances of your bot running

**Comment by SENPAY98K** [comment]
i was using for test, and i created new server with it only

![image](https://user-images.githubusercontent.com/77079047/188254511-8db900d8-bd0c-44d7-bfc0-b60bc45db0d0.png)
